//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// Boot from OpenAPI schema.
/// Schema path: #/components/schemas/Boot
/// </summary>
public partial class Boot
{
  [System.Text.Json.Serialization.JsonPropertyName("rescue")]
  public Dictionary<string, object?>? Rescue { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("linux")]
  public Dictionary<string, object?>? Linux { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("vnc")]
  public Dictionary<string, object?>? Vnc { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("windows")]
  public Windows? Windows { get; set; }
}
