//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// ErrorError from OpenAPI schema.
/// Schema path: #/components/schemas/ErrorError
/// </summary>
public partial class ErrorError
{
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public int? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("code")]
  public string? Code { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("missing")]
  public List<string?>? Missing { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("invalid")]
  public List<string?>? Invalid { get; set; }
}
