//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// FailoverGetAllResponse from OpenAPI schema.
/// Schema path: #/components/schemas/FailoverGetAllResponse
/// </summary>
public partial class FailoverGetAllResponse
{
  [System.Text.Json.Serialization.JsonPropertyName("failover")]
  public Failover2? Failover { get; set; }
}
