//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// FailoverRouteRequest (generated from inline request body).
/// Source: POST /failover/{ip} (requestBody)
/// </summary>
public partial class FailoverRouteRequest
{
  /// <summary>
  /// Target server ip address
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("active_server_ip")]
  public string? ActiveServerIp { get; set; }
}
