//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// FirewallTemplateGetResponseFirewallTemplate from OpenAPI schema.
/// Schema path: #/components/schemas/FirewallTemplateGetResponseFirewallTemplate
/// </summary>
public partial class FirewallTemplateGetResponseFirewallTemplate
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("filter_ipv6")]
  public bool? FilterIpv6 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("whitelist_hos")]
  public bool? WhitelistHos { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("is_default")]
  public bool? IsDefault { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rules")]
  public FirewallTemplateGetResponseFirewallTemplateRules? Rules { get; set; }
}
