//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// Input2 from OpenAPI schema.
/// Schema path: #/components/schemas/Input2
/// </summary>
public partial class Input2
{
  [System.Text.Json.Serialization.JsonPropertyName("ip_version")]
  public string? IpVersion { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("dst_ip")]
  public object? DstIp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("src_ip")]
  public string? SrcIp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("dst_port")]
  public string? DstPort { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("src_port")]
  public object? SrcPort { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("protocol")]
  public string? Protocol { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tcp_flags")]
  public object? TcpFlags { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public string? Action { get; set; }
}
