//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// IpSetTrafficWarningLimitsRequest (generated from inline request body).
/// Source: POST /ip/{ip} (requestBody)
/// </summary>
public partial class IpSetTrafficWarningLimitsRequest
{
  /// <summary>
  /// Hourly traffic in megabyte
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("traffic_hourly")]
  public int TrafficHourly { get; set; }

  /// <summary>
  /// Daily traffic in megabyte
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("traffic_daily")]
  public int TrafficDaily { get; set; }

  /// <summary>
  /// Montly traffic in gigabyte
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("traffic_monthly")]
  public int TrafficMonthly { get; set; }
}
