//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// Extension methods for converting between Request and Response models
/// </summary>
public static class ModelConversionExtensions
{
}
