//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// OrderServerTransactionGetAllResponseTransaction from OpenAPI schema.
/// Schema path: #/components/schemas/OrderServerTransactionGetAllResponseTransaction
/// </summary>
public partial class OrderServerTransactionGetAllResponseTransaction
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public DateTime? Date { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_number")]
  public int? ServerNumber { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_ip")]
  public string? ServerIp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authorized_key")]
  public List<OrderServerTransactionGetAllResponseTransactionAuthorizedKey>? AuthorizedKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("host_key")]
  public List<OrderServerTransactionGetAllResponseTransactionHostKey>? HostKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("comment")]
  public object? Comment { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("product")]
  public OrderServerTransactionGetAllResponseTransactionProduct? Product { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("addons")]
  public List<string?>? Addons { get; set; }
}
