//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// RdnsUpdateRequest (generated from inline request body).
/// Source: POST /rdns/{ip} (requestBody)
/// </summary>
public partial class RdnsUpdateRequest
{
  /// <summary>
  /// PTR record
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("ptr")]
  public string? Ptr { get; set; }
}
