//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// RdnsUpdateResponse from OpenAPI schema.
/// Schema path: #/components/schemas/RdnsUpdateResponse
/// </summary>
public partial class RdnsUpdateResponse
{
  [System.Text.Json.Serialization.JsonPropertyName("rdns")]
  public Rdns? Rdns { get; set; }
}
