//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// ServerCancellationGetResponseCancellation from OpenAPI schema.
/// Schema path: #/components/schemas/ServerCancellationGetResponseCancellation
/// </summary>
public partial class ServerCancellationGetResponseCancellation
{
  [System.Text.Json.Serialization.JsonPropertyName("server_ip")]
  public string? ServerIp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_ipv6_net")]
  public string? ServerIpv6Net { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_number")]
  public int? ServerNumber { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_name")]
  public string? ServerName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("earliest_cancellation_date")]
  public DateOnly? EarliestCancellationDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cancelled")]
  public bool? Cancelled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("reservation_possible")]
  public bool? ReservationPossible { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("reserved")]
  public bool? Reserved { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cancellation_date")]
  public object? CancellationDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cancellation_reason")]
  public List<string?>? CancellationReason { get; set; }
}
