//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// ServerGetResponseServer from OpenAPI schema.
/// Schema path: #/components/schemas/ServerGetResponseServer
/// </summary>
public partial class ServerGetResponseServer
{
  [System.Text.Json.Serialization.JsonPropertyName("server_ip")]
  public string? ServerIp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_ipv6_net")]
  public string? ServerIpv6Net { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_number")]
  public int? ServerNumber { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_name")]
  public string? ServerName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("product")]
  public string? Product { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("dc")]
  public string? Dc { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("traffic")]
  public string? Traffic { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cancelled")]
  public bool? Cancelled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("paid_until")]
  public DateOnly? PaidUntil { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ip")]
  public List<string?>? Ip { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("subnet")]
  public List<ServerGetResponseServerSubnet>? Subnet { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("reset")]
  public bool? Reset { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rescue")]
  public bool? Rescue { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("vnc")]
  public bool? Vnc { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("windows")]
  public bool? Windows { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("plesk")]
  public bool? Plesk { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cpanel")]
  public bool? Cpanel { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("wol")]
  public bool? Wol { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hot_swap")]
  public bool? HotSwap { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("linked_storagebox")]
  public int? LinkedStoragebox { get; set; }
}
