//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// Snapshotplan from OpenAPI schema.
/// Schema path: #/components/schemas/Snapshotplan
/// </summary>
public partial class Snapshotplan
{
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("minute")]
  public int? Minute { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hour")]
  public int? Hour { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("day_of_week")]
  public int? DayOfWeek { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("day_of_month")]
  public object? DayOfMonth { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("month")]
  public object? Month { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("max_snapshots")]
  public int? MaxSnapshots { get; set; }
}
