//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// StorageboxSubAccountGetResponseSubaccount from OpenAPI schema.
/// Schema path: #/components/schemas/StorageboxSubAccountGetResponseSubaccount
/// </summary>
public partial class StorageboxSubAccountGetResponseSubaccount
{
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accountid")]
  public string? Accountid { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server")]
  public string? Server { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("homedirectory")]
  public string? Homedirectory { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("samba")]
  public bool? Samba { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssh")]
  public bool? Ssh { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("external_reachability")]
  public bool? ExternalReachability { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webdav")]
  public bool? Webdav { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("readonly")]
  public bool? Readonly { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("createtime")]
  public DateTime? Createtime { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("comment")]
  public string? Comment { get; set; }
}
