//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// StorageboxGetAllResponseStoragebox from OpenAPI schema.
/// Schema path: #/components/schemas/StorageboxGetAllResponseStoragebox
/// </summary>
public partial class StorageboxGetAllResponseStoragebox
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("login")]
  public string? Login { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("product")]
  public string? Product { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cancelled")]
  public bool? Cancelled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("locked")]
  public bool? Locked { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("location")]
  public string? Location { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("linked_server")]
  public int? LinkedServer { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("paid_until")]
  public DateOnly? PaidUntil { get; set; }
}
