//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// Subnet3 from OpenAPI schema.
/// Schema path: #/components/schemas/Subnet3
/// </summary>
public partial class Subnet3
{
  [System.Text.Json.Serialization.JsonPropertyName("ip")]
  public string? Ip { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("mask")]
  public int? Mask { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("gateway")]
  public string? Gateway { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_ip")]
  public string? ServerIp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_number")]
  public int? ServerNumber { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("failover")]
  public bool? Failover { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("locked")]
  public bool? Locked { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("traffic_warnings")]
  public bool? TrafficWarnings { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("traffic_hourly")]
  public int? TrafficHourly { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("traffic_daily")]
  public int? TrafficDaily { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("traffic_monthly")]
  public int? TrafficMonthly { get; set; }
}
