//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// SubnetMacSetResponseMac from OpenAPI schema.
/// Schema path: #/components/schemas/SubnetMacSetResponseMac
/// </summary>
public partial class SubnetMacSetResponseMac
{
  [System.Text.Json.Serialization.JsonPropertyName("ip")]
  public string? Ip { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("mask")]
  public string? Mask { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("mac")]
  public string? Mac { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("possible_mac")]
  public Dictionary<string, string?>? PossibleMac { get; set; }
}
