//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// Traffic from OpenAPI schema.
/// Schema path: #/components/schemas/Traffic
/// </summary>
public partial class Traffic
{
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("from")]
  public DateOnly? From { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("to")]
  public DateOnly? To { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("data")]
  public Dictionary<string, object?>? Data { get; set; }
}
