//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// VswitchCreateResponse from OpenAPI schema.
/// Schema path: #/components/schemas/VswitchCreateResponse
/// </summary>
public partial class VswitchCreateResponse
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("vlan")]
  public int? Vlan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cancelled")]
  public bool? Cancelled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server")]
  public List<object?>? Server { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("subnet")]
  public List<object?>? Subnet { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cloud_network")]
  public List<object?>? CloudNetwork { get; set; }
}
