//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// VswitchCancelRequest (generated from inline request body).
/// Source: DELETE /vswitch/{vswitch_id} (requestBody)
/// </summary>
public partial class VswitchCancelRequest
{
  /// <summary>
  /// Date to which the vSwitch should be cancelled (format yyyy-MM-dd) or &quot;now&quot; to cancel immediately
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("cancellation_date")]
  public string? CancellationDate { get; set; }
}
