//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// WindowsDeactivateResponseWindows from OpenAPI schema.
/// Schema path: #/components/schemas/WindowsDeactivateResponseWindows
/// </summary>
public partial class WindowsDeactivateResponseWindows
{
  [System.Text.Json.Serialization.JsonPropertyName("server_ip")]
  public string? ServerIp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_ipv6_net")]
  public string? ServerIpv6Net { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_number")]
  public int? ServerNumber { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("os")]
  public List<string?>? Os { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("dist")]
  public List<string?>? Dist { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("lang")]
  public List<string?>? Lang { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("active")]
  public bool? Active { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public object? Password { get; set; }
}
