//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Robot.Models;

/// <summary>
/// WolGetResponseWol from OpenAPI schema.
/// Schema path: #/components/schemas/WolGetResponseWol
/// </summary>
public partial class WolGetResponseWol
{
  [System.Text.Json.Serialization.JsonPropertyName("server_ip")]
  public string? ServerIp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_ipv6_net")]
  public string? ServerIpv6Net { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("server_number")]
  public int? ServerNumber { get; set; }
}
