//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// AddNetworkSubnetRequest (generated from inline request body).
/// Source: POST /networks/{id}/actions/add_subnet (requestBody)
/// </summary>
public partial class AddNetworkSubnetRequest
{
  /// <summary>
  /// Type of subnet.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  /// <summary>
  /// IP range of the subnet.
  /// 
  /// Uses CIDR notation.
  /// 
  /// Must be a subnet of the parent [Networks](#tag/networks) ip_range.
  /// 
  /// Must not overlap with any other subnets or with any destinations in routes.
  /// 
  /// Minimum network size is /30. We highly recommend that you pick a larger subnet with a /24 netmask.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ip_range")]
  public string? IpRange { get; set; }

  /// <summary>
  /// Name of the [Network Zone](#tag/network-zones).
  /// 
  /// The [Location](#tag/locations) contains the network_zone it belongs to.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("network_zone")]
  public string? NetworkZone { get; set; }

  /// <summary>
  /// ID of the robot vSwitch.
  /// 
  /// Must be supplied if the subnet is of type vswitch.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("vswitch_id")]
  public long? VswitchId { get; set; }
}
