//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// AddNetworkRouteRequest (generated from inline request body).
/// Source: POST /networks/{id}/actions/add_route (requestBody)
/// </summary>
public partial class AddNetworkRouteRequest
{
  /// <summary>
  /// Destination network or host of the route.
  /// 
  /// Packages addressed for IPs matching the destination IP prefix will be send to the specified gateway.
  /// 
  /// Must be one of
  /// private IPv4 ranges of RFC1918
  /// or 0.0.0.0/0.
  /// 
  /// Must not overlap with
  /// an existing ip_range in any subnets
  /// or with any destinations in other routes
  /// or with 172.31.1.1.
  /// 
  /// 172.31.1.1 is being used as a gateway for the public network interface of [Servers](#tag/servers).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("destination")]
  public string? Destination { get; set; }

  /// <summary>
  /// Gateway of the route.
  /// 
  /// Packages addressed for the specified destination will be send to this IP address.
  /// 
  /// Cannot be
  /// the first IP of the networks ip_range,
  /// an IP behind a vSwitch or
  /// 172.31.1.1.
  /// 
  /// 172.31.1.1 is being used as a gateway for the public network interface of [Servers](#tag/servers).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("gateway")]
  public string? Gateway { get; set; }
}
