//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ApplyFirewallToResourcesRequest (generated from inline request body).
/// Source: POST /firewalls/{id}/actions/apply_to_resources (requestBody)
/// </summary>
public partial class ApplyFirewallToResourcesRequest
{
  /// <summary>
  /// Resources to apply the [Firewall](#tag/firewalls) to.
  /// 
  /// Extends existing resources.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("apply_to")]
  public List<object?>? ApplyTo { get; set; }
}
