//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// AssignPrimaryIpRequest (generated from inline request body).
/// Source: POST /primary_ips/{id}/actions/assign (requestBody)
/// </summary>
public partial class AssignPrimaryIpRequest
{
  /// <summary>
  /// Type of resource assigning the Primary IP to.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("assignee_type")]
  public string? AssigneeType { get; set; }

  /// <summary>
  /// ID of a resource of type assignee_type.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assignee_id")]
  public long AssigneeId { get; set; }
}
