//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// AssignFloatingIpRequest (generated from inline request body).
/// Source: POST /floating_ips/{id}/actions/assign (requestBody)
/// </summary>
public partial class AssignFloatingIpRequest
{
  /// <summary>
  /// [Server](#tag/servers) the [Floating IP](#tag/floating-ips) is assigned to.
  /// 
  /// null if not assigned.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("server")]
  public long? Server { get; set; }
}
