//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// AttachServerToNetworkRequest (generated from inline request body).
/// Source: POST /servers/{id}/actions/attach_to_network (requestBody)
/// </summary>
public partial class AttachServerToNetworkRequest
{
  /// <summary>
  /// ID of an existing network to attach the Server to.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("network")]
  public long Network { get; set; }

  /// <summary>
  /// IP to request to be assigned to this Server; if you do not provide this then you will be auto assigned an IP address.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ip")]
  public string? Ip { get; set; }

  /// <summary>
  /// Additional IPs to be assigned to this Server.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("alias_ips")]
  public List<string?>? AliasIps { get; set; }

  /// <summary>
  /// IP range in CIDR block notation of the subnet to attach to.
  /// 
  /// This allows for auto assigning an IP address for a specific subnet.
  /// Providing ip that is not part of ip_range will result in an error.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ip_range")]
  public string? IpRange { get; set; }
}
