//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// AttachVolumeRequest (generated from inline request body).
/// Source: POST /volumes/{id}/actions/attach (requestBody)
/// </summary>
public partial class AttachVolumeRequest
{
  /// <summary>
  /// ID of the Server the Volume will be attached to.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("server")]
  public long Server { get; set; }

  /// <summary>
  /// Auto-mount the Volume after attaching it.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("automount")]
  public bool? Automount { get; set; }
}
