//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ChangeLoadBalancerTypeRequest (generated from inline request body).
/// Source: POST /load_balancers/{id}/actions/change_type (requestBody)
/// </summary>
public partial class ChangeLoadBalancerTypeRequest
{
  /// <summary>
  /// ID or name of Load Balancer type the Load Balancer should migrate to.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("load_balancer_type")]
  public string? LoadBalancerType { get; set; }
}
