//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ChangeServerTypeRequest (generated from inline request body).
/// Source: POST /servers/{id}/actions/change_type (requestBody)
/// </summary>
public partial class ChangeServerTypeRequest
{
  /// <summary>
  /// If false, do not upgrade the disk (this allows downgrading the Server type later).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("upgrade_disk")]
  public bool UpgradeDisk { get; set; }

  /// <summary>
  /// ID or name of Server type the Server should migrate to.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("server_type")]
  public string? ServerType { get; set; }
}
