//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ChangePrimaryIpProtectionRequest (generated from inline request body).
/// Source: POST /primary_ips/{id}/actions/change_protection (requestBody)
/// 
/// Protection configuration for the Resource.
/// </summary>
public partial class ChangePrimaryIpProtectionRequest
{
  /// <summary>
  /// Prevent the Resource from being deleted.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("delete")]
  public bool Delete { get; set; }
}
