//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ChangeZoneTtlRequest (generated from inline request body).
/// Source: POST /zones/{id_or_name}/actions/change_ttl (requestBody)
/// </summary>
public partial class ChangeZoneTtlRequest
{
  /// <summary>
  /// Default Time To Live (TTL) of the [Zone](#tag/zones).
  /// 
  /// Must be in between 60s and 2147483647s.
  /// 
  /// This TTL is used for [RRSets](#tag/zone-rrsets) that do not explicitly define a TTL.
  /// 
  /// </summary>
  [Required]
  [Range(60, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("ttl")]
  public int Ttl { get; set; }
}
