//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ChangeServerAliasIpsRequest (generated from inline request body).
/// Source: POST /servers/{id}/actions/change_alias_ips (requestBody)
/// </summary>
public partial class ChangeServerAliasIpsRequest
{
  /// <summary>
  /// ID of an existing Network already attached to the Server.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("network")]
  public long Network { get; set; }

  /// <summary>
  /// New alias IPs to set for this Server.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("alias_ips")]
  public List<string?>? AliasIps { get; set; }
}
