//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ChangeServerDnsPtrRequest (generated from inline request body).
/// Source: POST /servers/{id}/actions/change_dns_ptr (requestBody)
/// </summary>
public partial class ChangeServerDnsPtrRequest
{
  /// <summary>
  /// Single IPv4 or IPv6 address to create pointer for.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("ip")]
  public string? Ip { get; set; }

  /// <summary>
  /// Domain Name to point to.
  /// 
  /// PTR record content used for reverse DNS. Set to null to reset (IPv4) to the default value or remove (IPv6) the record.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("dns_ptr")]
  public string? DnsPtr { get; set; }
}
