//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ChangeZoneRrsetTtlRequest (generated from inline request body).
/// Source: POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_ttl (requestBody)
/// </summary>
public partial class ChangeZoneRrsetTtlRequest
{
  /// <summary>
  /// Time To Live (TTL) of the [RRSet](#tag/zone-rrsets).
  /// 
  /// Must be in between 60s and 2147483647s.
  /// 
  /// If not set, the [Zone&apos;s](#tag/zones) Default TTL is used.
  /// 
  /// </summary>
  [Required]
  [Range(60, 2147483647)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("ttl")]
  public int? Ttl { get; set; }
}
