//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ChangeZoneRrsetProtectionRequest (generated from inline request body).
/// Source: POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/change_protection (requestBody)
/// 
/// Protection of the [RRSet](#tag/zone-rrsets).
/// 
/// </summary>
public partial class ChangeZoneRrsetProtectionRequest
{
  /// <summary>
  /// Prevent the Resource from being changed.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("change")]
  public bool Change { get; set; }
}
