//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ChangeNetworkIpRangeRequest (generated from inline request body).
/// Source: POST /networks/{id}/actions/change_ip_range (requestBody)
/// </summary>
public partial class ChangeNetworkIpRangeRequest
{
  /// <summary>
  /// IP range of the [Network](#tag/networks).
  /// 
  /// Uses CIDR notation.
  /// 
  /// Must span all included subnets. Must be one of the private IPv4 ranges of RFC1918.
  /// 
  /// Minimum network size is /24. We highly recommend that you pick a larger [Network](#tag/networks) with a /16 netmask.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("ip_range")]
  public string? IpRange { get; set; }
}
