//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateServerRequest (generated from inline request body).
/// Source: POST /servers (requestBody)
/// </summary>
public partial class CreateServerRequest
{
  /// <summary>
  /// Name of the Server to create (must be unique per Project and a valid hostname as per RFC 1123).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// ID or name of the Location to create the Server in (must not be used together with datacenter).
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("location")]
  public string? Location { get; set; }

  /// <summary>
  /// Deprecated**: This property is deprecated and will be removed after the 1 July 2026.
  /// Use the location property instead.
  /// 
  /// ID or name of the Data Center to create Server in (must not be used together with location).
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("datacenter")]
  public string? Datacenter { get; set; }

  /// <summary>
  /// ID or name of the Server type this Server should be created with.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("server_type")]
  public string? ServerType { get; set; }

  /// <summary>
  /// This automatically triggers a [Power on a Server-Server Action](#tag/server-actions/poweron_server) after the creation is finished and is returned in the next_actions response object.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("start_after_create")]
  public bool? StartAfterCreate { get; set; }

  /// <summary>
  /// ID or name of the Image the Server is created from.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("image")]
  public string? Image { get; set; }

  /// <summary>
  /// ID of the Placement Group the Server should be in.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("placement_group")]
  public long? PlacementGroup { get; set; }

  /// <summary>
  /// SSH key IDs (integer) or names (string) which should be injected into the Server at creation time.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ssh_keys")]
  public List<string?>? SshKeys { get; set; }

  /// <summary>
  /// Volume IDs which should be attached to the Server at the creation time. Volumes must be in the same Location.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("volumes")]
  public List<long>? Volumes { get; set; }

  /// <summary>
  /// Network IDs which should be attached to the Server private network interface at the creation time.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("networks")]
  public List<long>? Networks { get; set; }

  /// <summary>
  /// Firewalls which should be applied on the Server&apos;s public network interface at creation time.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("firewalls")]
  public List<object?>? Firewalls { get; set; }

  /// <summary>
  /// Cloud-Init user data to use during Server creation. This field is limited to 32KiB.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("user_data")]
  public string? UserData { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }

  /// <summary>
  /// Auto-mount Volumes after attach.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("automount")]
  public bool? Automount { get; set; }

  /// <summary>
  /// Public Network options.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("public_net")]
  public object? PublicNet { get; set; }
}
