//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateZoneRequest (generated from inline request body).
/// Source: POST /zones (requestBody)
/// </summary>
public partial class CreateZoneRequest
{
  /// <summary>
  /// Name of the [Zone](#tag/zones).
  /// 
  /// All names with [well-known public suffixes](https://publicsuffix.org/) (e.g. .de,
  /// .com, .co.uk) are supported. Subdomains are not supported.
  /// 
  /// The name must be in lower case and must not end with a dot.
  /// [Internationalized domain
  /// names](https://en.wikipedia.org/wiki/Internationalized_domain_name) must be
  /// transcribed to [Punycode](https://wikipedia.org/wiki/Punycode) representation with
  /// ACE prefix, e.g. xn--mnchen-3ya.de (münchen.de).
  /// 
  /// </summary>
  [Required]
  [MaxLength(255)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Mode of the [Zone](#tag/zones).
  /// 
  /// For more information, see [Zone Modes](#tag/zones/zone-modes).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("mode")]
  public string? Mode { get; set; }

  /// <summary>
  /// Default Time To Live (TTL) of the [Zone](#tag/zones).
  /// 
  /// Must be in between 60s and 2147483647s.
  /// 
  /// This TTL is used for [RRSets](#tag/zone-rrsets) that do not explicitly define a TTL.
  /// 
  /// </summary>
  [Range(60, 2147483647)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ttl")]
  public int? Ttl { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }

  /// <summary>
  /// Primary nameservers of the [Zone](#tag/zones).
  /// 
  /// Only applicable for [Zones](#tag/zones) in secondary mode.
  /// Ignored for [Zones](#tag/zones) in primary mode.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("primary_nameservers")]
  public List<object?>? PrimaryNameservers { get; set; }

  /// <summary>
  /// [RRSets](#tag/zone-rrsets) to be added to the [Zone](#tag/zones).
  /// 
  /// Only applicable for [Zones](#tag/zones) in primary mode.
  /// Ignored for [Zones](#tag/zones) in secondary mode.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("rrsets")]
  public List<object?>? Rrsets { get; set; }

  /// <summary>
  /// Zone file to import.
  /// 
  /// Only applicable for [Zones](#tag/zones) in primary mode.
  /// Ignored for [Zones](#tag/zones) in secondary mode.
  /// 
  /// If provided, rrsets must be empty.
  /// 
  /// See [Zone file import](#tag/zones/zone-file-import) for more details.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("zonefile")]
  public string? Zonefile { get; set; }
}
