//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateNetworkRequest (generated from inline request body).
/// Source: POST /networks (requestBody)
/// </summary>
public partial class CreateNetworkRequest
{
  /// <summary>
  /// Name of the [Network](#tag/networks).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// IP range of the [Network](#tag/networks).
  /// 
  /// Uses CIDR notation.
  /// 
  /// Must span all included subnets. Must be one of the private IPv4 ranges of RFC1918.
  /// 
  /// Minimum network size is /24. We highly recommend that you pick a larger [Network](#tag/networks) with a /16 netmask.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("ip_range")]
  public string? IpRange { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }

  /// <summary>
  /// Array of subnets to allocate.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("subnets")]
  public List<object?>? Subnets { get; set; }

  /// <summary>
  /// Array of routes set in this [Network](#tag/networks).
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("routes")]
  public List<object?>? Routes { get; set; }

  /// <summary>
  /// Toggle to expose routes to the [Networks](#tag/networks) vSwitch.
  /// 
  /// Indicates if the routes from this [Network](#tag/networks) should be exposed to the vSwitch in this [Network](#tag/networks). Only takes effect if a [vSwitch is setup](https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch) in this [Network](#tag/networks).
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("expose_routes_to_vswitch")]
  public bool? ExposeRoutesToVswitch { get; set; }
}
