//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateFirewallRequestApplyTo from OpenAPI schema.
/// Schema path: #/components/schemas/CreateFirewallRequestApplyTo
/// </summary>
public partial class CreateFirewallRequestApplyTo
{
  /// <summary>
  /// Type of the resource.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  /// <summary>
  /// [Server](#tag/servers) the [Firewall](#tag/firewalls) is applied to.
  /// 
  /// Only set for type server, otherwise null.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("server")]
  public CreateFirewallRequestApplyToServer? Server { get; set; }

  /// <summary>
  /// [Label Selector](#description/label-selector) the [Firewall](#tag/firewalls) is applied to.
  /// 
  /// Only set for type label_selector, otherwise null.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("label_selector")]
  public TargetTypeLabelSelectorLabelSelector? LabelSelector { get; set; }
}
