//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateZoneRrsetRequest (generated from inline request body).
/// Source: POST /zones/{id_or_name}/rrsets (requestBody)
/// </summary>
public partial class CreateZoneRrsetRequest
{
  /// <summary>
  /// Name of the [RRSet](#tag/zone-rrsets).
  /// 
  /// The name must be in lower case, and must not end with a dot or the [Zone](#tag/zones)
  /// name. Names containing non-ASCII characters must be transcribed to
  /// [Punycode](https://wikipedia.org/wiki/Punycode) representation with ACE prefix, e.g.
  /// xn--4bi (✉️).
  /// 
  /// For the [Zone](#tag/zones) apex, use @.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Type of the [RRSet](#tag/zone-rrsets).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  /// <summary>
  /// Time To Live (TTL) of the [RRSet](#tag/zone-rrsets).
  /// 
  /// Must be in between 60s and 2147483647s.
  /// 
  /// If not set, the [Zone&apos;s](#tag/zones) Default TTL is used.
  /// 
  /// </summary>
  [Range(60, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("ttl")]
  public int? Ttl { get; set; }

  /// <summary>
  /// Records of the [RRSet](#tag/zone-rrsets).
  /// 
  /// Must not be empty and must only contain distinct record values.
  /// The order of records returned in responses is not guaranteed to be consistent.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("records")]
  public List<object?>? Records { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }
}
