//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateServerImageRequest (generated from inline request body).
/// Source: POST /servers/{id}/actions/create_image (requestBody)
/// </summary>
public partial class CreateServerImageRequest
{
  /// <summary>
  /// Description of the Image, will be auto-generated if not set.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Type of Image to create.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }
}
