//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateServerRequestPublicNet from OpenAPI schema.
/// Schema path: #/components/schemas/CreateServerRequestPublicNet
/// 
/// Public Network options.
/// </summary>
public partial class CreateServerRequestPublicNet
{
  /// <summary>
  /// Attach an IPv4 on the public NIC. If false, no IPv4 address will be attached.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("enable_ipv4")]
  public bool? EnableIpv4 { get; set; }

  /// <summary>
  /// Attach an IPv6 on the public NIC. If false, no IPv6 address will be attached.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("enable_ipv6")]
  public bool? EnableIpv6 { get; set; }

  /// <summary>
  /// ID of the ipv4 Primary IP to use. If omitted and enable_ipv4 is true, a new ipv4 Primary IP will automatically be created.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ipv4")]
  public int? Ipv4 { get; set; }

  /// <summary>
  /// ID of the ipv6 Primary IP to use. If omitted and enable_ipv6 is true, a new ipv6 Primary IP will automatically be created.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ipv6")]
  public int? Ipv6 { get; set; }
}
