//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateFloatingIpRequest (generated from inline request body).
/// Source: POST /floating_ips (requestBody)
/// </summary>
public partial class CreateFloatingIpRequest
{
  /// <summary>
  /// The Floating IP type.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  /// <summary>
  /// [Server](#tag/servers) the [Floating IP](#tag/floating-ips) is assigned to.
  /// 
  /// null if not assigned.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("server")]
  public long? Server { get; set; }

  /// <summary>
  /// Home [Location](#tag/locations) for the [Floating IP](#tag/floating-ips).
  /// 
  /// Either the ID or the name of the [Location](#tag/locations).
  /// 
  /// Only optional if no [Server](#tag/servers) is provided. Routing is optimized for this [Locations](#tag/locations).
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("home_location")]
  public object? HomeLocation { get; set; }

  /// <summary>
  /// Description of the Resource.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Name of the Resource. Must be unique per Project.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }
}
