//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateZoneRrsetRequestRecords from OpenAPI schema.
/// Schema path: #/components/schemas/CreateZoneRrsetRequestRecords
/// 
/// Record of a [RRSet](#tag/zone-rrsets).
/// 
/// The value is used to identify the record in an [RRSet](#tag/zone-rrsets).
/// 
/// </summary>
public partial class CreateZoneRrsetRequestRecords
{
  /// <summary>
  /// Value of the record.
  /// 
  /// For details about accepted values, see the [DNS record types documentation](https://docs.hetzner.com/networking/dns/record-types/overview/).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public string? Value { get; set; }

  /// <summary>
  /// Comment of the record.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("comment")]
  public string? Comment { get; set; }
}
