//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateCertificateRequest (generated from inline request body).
/// Source: POST /certificates (requestBody)
/// </summary>
public partial class CreateCertificateRequest
{
  /// <summary>
  /// Name of the Certificate.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }

  /// <summary>
  /// Choose between uploading a Certificate in PEM format or requesting a managed *Let&apos;s Encrypt* Certificate.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  /// <summary>
  /// Certificate and chain in PEM format, in order so that each record directly certifies the one preceding. Required for type uploaded Certificates.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("certificate")]
  public string? Certificate { get; set; }

  /// <summary>
  /// Certificate key in PEM format. Required for type uploaded Certificates.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("private_key")]
  public string? PrivateKey { get; set; }

  /// <summary>
  /// Domains and subdomains that should be contained in the Certificate issued by *Let&apos;s Encrypt*. Required for type managed Certificates.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("domain_names")]
  public List<string?>? DomainNames { get; set; }
}
