//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreatePrimaryIpRequest (generated from inline request body).
/// Source: POST /primary_ips (requestBody)
/// </summary>
public partial class CreatePrimaryIpRequest
{
  /// <summary>
  /// Name of the Resource. Must be unique per Project.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }

  /// <summary>
  /// [Primary IP](#tag/primary-ips) type.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  /// <summary>
  /// Deprecated**: This property is deprecated and will be removed after 1 July 2026.
  /// Use the location key instead.
  /// 
  /// [Data Center](#tag/data-centers) ID or name.
  /// 
  /// The [Primary IP](#tag/primary-ips) will be bound to this [Data Center](#tag/data-centers).
  /// Omit if assignee_id/assignee_type or location are provided.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("datacenter")]
  public object? Datacenter { get; set; }

  /// <summary>
  /// [Location](#tag/locations) ID or name the [Primary IP](#tag/primary-ips) will be bound to.
  /// 
  /// Omit if assignee_id/assignee_type or datacenter are provided.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("location")]
  public object? Location { get; set; }

  /// <summary>
  /// Type of resource the [Primary IP](#tag/primary-ips) can get assigned to.
  /// 
  /// Currently [Primary IPs](#tag/primary-ips) can only be assigned to [Servers](#tag/servers),
  /// therefore this field must be set to server.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("assignee_type")]
  public string? AssigneeType { get; set; }

  /// <summary>
  /// ID of resource to assign the [Primary IP](#tag/primary-ips) to.
  /// 
  /// Omitted if the [Primary IP](#tag/primary-ips) should not get assigned.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assignee_id")]
  public long? AssigneeId { get; set; }

  /// <summary>
  /// Auto deletion state.
  /// 
  /// If enabled the [Primary IP](#tag/primary-ips) will be deleted once the assigned resource gets deleted.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("auto_delete")]
  public bool? AutoDelete { get; set; }
}
