//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateFirewallRequestRules from OpenAPI schema.
/// Schema path: #/components/schemas/CreateFirewallRequestRules
/// </summary>
public partial class CreateFirewallRequestRules
{
  /// <summary>
  /// Description of the rule.
  /// </summary>
  [MaxLength(255)]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Traffic direction in which the rule should be applied to.
  /// 
  /// Use source_ips for direction in and destination_ips for direction out to specify IPs.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("direction")]
  public string? Direction { get; set; }

  /// <summary>
  /// List of permitted IPv4/IPv6 addresses for incoming traffic.
  /// 
  /// The direction must be set to in.
  /// 
  /// IPs must be provided in [CIDR block notation](https://wikipedia.org/wiki/CIDR). You can specify 100 CIDR
  /// blocks at most.
  /// 
  /// The CIDR blocks may refer to networks (with empty host bits) or single hosts.
  /// For example, a network could be defined with 10.0.1.0/24 or 2001:db8:ff00:42::/64,
  /// and a single host with 10.0.1.1/32 or 2001:db8:ff00:42::8329/128.
  /// 
  /// Use 0.0.0.0/0 to allow any IPv4 addresses and ::/0 to allow any IPv6 addresses.
  /// 
  /// IPv6 CIDRs will be transformed to their canonical form according to [RFC5952](https://datatracker.ietf.org/doc/html/rfc5952#section-4).
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("source_ips")]
  public List<string?>? SourceIps { get; set; }

  /// <summary>
  /// List of permitted IPv4/IPv6 addresses for outgoing traffic.
  /// 
  /// The direction must be set to out.
  /// 
  /// IPs must be in [CIDR block notation](https://wikipedia.org/wiki/CIDR). You can specify 100 CIDR
  /// blocks at most.
  /// 
  /// The CIDR blocks may refer to networks (with empty host bits) or single hosts.
  /// For example, a network could be defined with 10.0.1.0/24 or 2001:db8:ff00:42::/64,
  /// and a single host with 10.0.1.1/32 or 2001:db8:ff00:42::8329/128.
  /// 
  /// Use 0.0.0.0/0 to allow any IPv4 addresses and ::/0 to allow any IPv6 addresses.
  /// 
  /// IPv6 CIDRs will be transformed to their canonical form according to [RFC5952](https://datatracker.ietf.org/doc/html/rfc5952#section-4).
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("destination_ips")]
  public List<string?>? DestinationIps { get; set; }

  /// <summary>
  /// Network protocol to apply the rule for.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("protocol")]
  public string? Protocol { get; set; }

  /// <summary>
  /// Port or port range to apply the rule for.
  /// 
  /// Only applicable for protocols tcp and udp.
  /// 
  /// A port range can be specified by separating lower and upper bounds with a dash. 1024-5000 will include
  /// all ports starting from 1024 up to port 5000.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("port")]
  public string? Port { get; set; }
}
