//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// CreateFirewallRequestApplyToServer from OpenAPI schema.
/// Schema path: #/components/schemas/CreateFirewallRequestApplyToServer
/// 
/// [Server](#tag/servers) the [Firewall](#tag/firewalls) is applied to.
/// 
/// Only set for type server, otherwise null.
/// 
/// </summary>
public partial class CreateFirewallRequestApplyToServer
{
  /// <summary>
  /// ID of the [Server](#tag/servers).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public long Id { get; set; }
}
