//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// DetachLoadBalancerFromNetworkRequest (generated from inline request body).
/// Source: POST /load_balancers/{id}/actions/detach_from_network (requestBody)
/// </summary>
public partial class DetachLoadBalancerFromNetworkRequest
{
  /// <summary>
  /// ID of an existing network to detach the Load Balancer from.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("network")]
  public long Network { get; set; }
}
