//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ImportZoneZonefileRequest (generated from inline request body).
/// Source: POST /zones/{id_or_name}/actions/import_zonefile (requestBody)
/// </summary>
public partial class ImportZoneZonefileRequest
{
  /// <summary>
  /// Zone file to import.
  /// 
  /// See [Zone file import](#tag/zones/zone-file-import) for more details.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("zonefile")]
  public string? Zonefile { get; set; }
}
