//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// LoadBalancerHealthCheckRequest from OpenAPI schema.
/// Schema path: #/components/schemas/LoadBalancerHealthCheckRequest
/// </summary>
public partial class LoadBalancerHealthCheckRequest
{
  /// <summary>
  /// Type of the health check.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("protocol")]
  public string? Protocol { get; set; }

  /// <summary>
  /// Port the health check will be performed on.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("port")]
  public int Port { get; set; }

  /// <summary>
  /// Time interval in seconds health checks are performed.
  /// </summary>
  [Required]
  [Range(3, 60)]
  [System.Text.Json.Serialization.JsonPropertyName("interval")]
  public int Interval { get; set; }

  /// <summary>
  /// Time in seconds after an attempt is considered a timeout.
  /// </summary>
  [Required]
  [Range(1, 60)]
  [System.Text.Json.Serialization.JsonPropertyName("timeout")]
  public int Timeout { get; set; }

  /// <summary>
  /// Unsuccessful retries needed until a target is considered unhealthy; an unhealthy target needs the same number of successful retries to become healthy again.
  /// </summary>
  [Required]
  [Range(1, 5)]
  [System.Text.Json.Serialization.JsonPropertyName("retries")]
  public int Retries { get; set; }

  /// <summary>
  /// Additional configuration for protocol http.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("http")]
  public object? Http { get; set; }
}
