//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// Extension methods for converting between Request and Response models
/// </summary>
public static class ModelConversionExtensions
{
}
