//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// RebuildServerRequest (generated from inline request body).
/// Source: POST /servers/{id}/actions/rebuild (requestBody)
/// </summary>
public partial class RebuildServerRequest
{
  /// <summary>
  /// ID or name of Image to rebuilt from.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("image")]
  public string? Image { get; set; }

  /// <summary>
  /// Cloud-Init user data to use during Server rebuild. This field is limited to 32KiB. If not specified, the Server&apos;s previous user_data value will be re-used (if any was set).
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("user_data")]
  public string? UserData { get; set; }
}
