//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// RemoveFirewallFromResourcesRequest (generated from inline request body).
/// Source: POST /firewalls/{id}/actions/remove_from_resources (requestBody)
/// </summary>
public partial class RemoveFirewallFromResourcesRequest
{
  /// <summary>
  /// Resources to remove the [Firewall](#tag/firewalls) from.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("remove_from")]
  public List<object?>? RemoveFrom { get; set; }
}
