//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// RemoveLoadBalancerTargetRequestServer from OpenAPI schema.
/// Schema path: #/components/schemas/RemoveLoadBalancerTargetRequestServer
/// 
/// Configuration for type Server, only valid and required if type is server.
/// </summary>
public partial class RemoveLoadBalancerTargetRequestServer
{
  /// <summary>
  /// ID of the Server.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public long Id { get; set; }

  /// <summary>
  /// Optional public IP of the Server to use as target.
  /// Must be the Primary IPv4 of the Server, or an IPv6 host address within IPv6 /64 subnet of the Server. If omitted, the Primary IPv4 of the Server is used. Must not be a private IP and is only valid for public targets.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ip")]
  public string? Ip { get; set; }
}
