//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ResizeVolumeRequest (generated from inline request body).
/// Source: POST /volumes/{id}/actions/resize (requestBody)
/// </summary>
public partial class ResizeVolumeRequest
{
  /// <summary>
  /// New Volume size in GB (must be greater than current size).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("size")]
  public decimal Size { get; set; }
}
