//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ServiceTCP from OpenAPI schema.
/// Schema path: #/components/schemas/ServiceTCP
/// </summary>
public partial class ServiceTcp
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("protocol")]
  public string? Protocol { get; set; }

  /// <summary>
  /// Port the Load Balancer listens on.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("listen_port")]
  public int ListenPort { get; set; }

  /// <summary>
  /// Port the Load Balancer will balance to.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("destination_port")]
  public int DestinationPort { get; set; }

  /// <summary>
  /// Is Proxyprotocol enabled or not.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("proxyprotocol")]
  public bool Proxyprotocol { get; set; }

  /// <summary>
  /// Service health check.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("health_check")]
  public object? HealthCheck { get; set; }
}
