//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ServiceTcpHealthCheckHttp from OpenAPI schema.
/// Schema path: #/components/schemas/ServiceTcpHealthCheckHttp
/// 
/// Additional configuration for protocol http.
/// </summary>
public partial class ServiceTcpHealthCheckHttp
{
  /// <summary>
  /// Host header to send in the HTTP request. May not contain spaces, percent or backslash symbols. Can be null, in that case no host header is sent.
  /// </summary>
  [Required]
  [MaxLength(128)]
  [System.Text.Json.Serialization.JsonPropertyName("domain")]
  public string? Domain { get; set; }

  /// <summary>
  /// HTTP path to use for health checks. May not contain literal spaces, use percent-encoding instead.
  /// </summary>
  [Required]
  [MinLength(1)]
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("path")]
  public string? Path { get; set; }

  /// <summary>
  /// String that must be contained in HTTP response in order to pass the health check.
  /// </summary>
  [MaxLength(256)]
  [System.Text.Json.Serialization.JsonPropertyName("response")]
  public string? Response { get; set; }

  /// <summary>
  /// List of returned HTTP status codes in order to pass the health check. Supports the wildcards ? for exactly one character and * for multiple ones.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status_codes")]
  public List<string?>? StatusCodes { get; set; }

  /// <summary>
  /// Use HTTPS for health check.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tls")]
  public bool? Tls { get; set; }
}
