//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ServiceHttpProtocolHttp from OpenAPI schema.
/// Schema path: #/components/schemas/ServiceHttpProtocolHttp
/// 
/// Configuration option for protocol http.
/// </summary>
public partial class ServiceHttpProtocolHttp
{
  /// <summary>
  /// Name of the cookie used for sticky sessions.
  /// </summary>
  [Required]
  [MinLength(1)]
  [MaxLength(100)]
  [System.Text.Json.Serialization.JsonPropertyName("cookie_name")]
  public string? CookieName { get; set; }

  /// <summary>
  /// Lifetime of the cookie used for sticky sessions (in seconds).
  /// </summary>
  [Required]
  [Range(30, 86400)]
  [System.Text.Json.Serialization.JsonPropertyName("cookie_lifetime")]
  public int CookieLifetime { get; set; }

  /// <summary>
  /// Idle timeout in seconds for the client and server side.
  /// </summary>
  [Required]
  [Range(30, 300)]
  [System.Text.Json.Serialization.JsonPropertyName("timeout_idle")]
  public int TimeoutIdle { get; set; }

  /// <summary>
  /// Use sticky sessions.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("sticky_sessions")]
  public bool StickySessions { get; set; }
}
