//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// SetFirewallRulesRequest (generated from inline request body).
/// Source: POST /firewalls/{id}/actions/set_rules (requestBody)
/// </summary>
public partial class SetFirewallRulesRequest
{
  /// <summary>
  /// Array of rules.
  /// 
  /// Rules are limited to 50 entries per [Firewall](#tag/firewalls) and [500 effective rules](https://docs.hetzner.com/cloud/firewalls/overview#limits).
  /// 
  /// Existing rules will be replaced.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("rules")]
  public List<object?>? Rules { get; set; }
}
