//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// TargetTypeIP from OpenAPI schema.
/// Schema path: #/components/schemas/TargetTypeIP
/// </summary>
public partial class TargetTypeIp
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  /// <summary>
  /// IP target where the traffic should be routed to. It is only possible to use the (Public or vSwitch) IPs of Hetzner Online Root Servers belonging to the project owner. IPs belonging to other users are blocked. Additionally IPs belonging to services provided by Hetzner Cloud (Servers, Load Balancers, ...) are blocked as well. Only present for target type ip.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ip")]
  public object? Ip { get; set; }

  /// <summary>
  /// List of health statuses of the services on this target. Only present for target types &quot;server&quot; and &quot;ip&quot;.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("health_status")]
  public List<object?>? HealthStatus { get; set; }
}
