//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// TargetTypeServerServer from OpenAPI schema.
/// Schema path: #/components/schemas/TargetTypeServerServer
/// 
/// Server where the traffic should be routed to. Only present for target type &quot;server&quot;.
/// </summary>
public partial class TargetTypeServerServer
{
  /// <summary>
  /// ID of the Server.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public long Id { get; set; }

  /// <summary>
  /// IP of the Server that the traffic is routed to. Either the Server&apos;s primary IPv4 or, if an IPv6 was specified when adding the target, an IPv6 within the Server&apos;s /64 subnet.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ip")]
  public string? Ip { get; set; }
}
