//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// TargetTypeServerHealthStatus from OpenAPI schema.
/// Schema path: #/components/schemas/TargetTypeServerHealthStatus
/// </summary>
public partial class TargetTypeServerHealthStatus
{
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("listen_port")]
  public int ListenPort { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  /// <summary>
  /// Additional details about why the health check failed. Only present when status is unhealthy.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("detail")]
  public string? Detail { get; set; }

  /// <summary>
  /// HTTP status code returned by the target during the last health check. Only present when status is unhealthy and detail is unexpected_http_status.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("http_status_code")]
  public int? HttpStatusCode { get; set; }
}
