//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// UpdateZoneRrsetRecordsRequest (generated from inline request body).
/// Source: POST /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}/actions/update_records (requestBody)
/// </summary>
public partial class UpdateZoneRrsetRecordsRequest
{
  /// <summary>
  /// Records to update in the [RRSet](#tag/zone-rrsets).
  /// 
  /// Must not be empty and must only contain distinct record values.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("records")]
  public List<object?>? Records { get; set; }
}
