//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// UpdateNetworkRequest (generated from inline request body).
/// Source: PUT /networks/{id} (requestBody)
/// </summary>
public partial class UpdateNetworkRequest
{
  /// <summary>
  /// New [Network](#tag/networks) name.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// 
  /// Note that the set of [Labels](#description/labels) provided in the request will overwrite the
  /// existing one.
  /// 
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }

  /// <summary>
  /// Toggle to expose routes to the [Networks](#tag/networks) vSwitch.
  /// 
  /// Indicates if the routes from this [Network](#tag/networks) should be exposed to the vSwitch in this [Network](#tag/networks). Only takes effect if a [vSwitch is setup](https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch) in this [Network](#tag/networks).
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("expose_routes_to_vswitch")]
  public bool? ExposeRoutesToVswitch { get; set; }
}
