//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ZonePrimary from OpenAPI schema.
/// Schema path: #/components/schemas/ZonePrimary
/// </summary>
public partial class ZonePrimary
{
  /// <summary>
  /// ID of the [Zone](#tag/zones).
  /// </summary>
  [Required]
  [Range(1, 9007199254740991)]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public long Id { get; set; }

  /// <summary>
  /// Name of the [Zone](#tag/zones).
  /// 
  /// All names with [well-known public suffixes](https://publicsuffix.org/) (e.g. .de,
  /// .com, .co.uk) are supported. Subdomains are not supported.
  /// 
  /// The name must be in lower case and must not end with a dot.
  /// [Internationalized domain
  /// names](https://en.wikipedia.org/wiki/Internationalized_domain_name) must be
  /// transcribed to [Punycode](https://wikipedia.org/wiki/Punycode) representation with
  /// ACE prefix, e.g. xn--mnchen-3ya.de (münchen.de).
  /// 
  /// </summary>
  [Required]
  [MaxLength(255)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public DateTime Created { get; set; }

  /// <summary>
  /// Primary nameservers of the [Zone](#tag/zones).
  /// 
  /// Only set if [Zone](#tag/zones) is in [secondary mode](#tag/zones/zone-modes), otherwise empty.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("primary_nameservers")]
  public List<object?>? PrimaryNameservers { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }

  /// <summary>
  /// Protection configuration for the Resource.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("protection")]
  public object? Protection { get; set; }

  /// <summary>
  /// Default Time To Live (TTL) of the [Zone](#tag/zones).
  /// 
  /// Must be in between 60s and 2147483647s.
  /// 
  /// This TTL is used for [RRSets](#tag/zone-rrsets) that do not explicitly define a TTL.
  /// 
  /// </summary>
  [Required]
  [Range(60, 2147483647)]
  [System.Text.Json.Serialization.JsonPropertyName("ttl")]
  public int Ttl { get; set; }

  /// <summary>
  /// Status of the [Zone](#tag/zones).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  /// <summary>
  /// Number of resource records (RR) within the [Zone](#tag/zones).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("record_count")]
  public int RecordCount { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("authoritative_nameservers")]
  public object? AuthoritativeNameservers { get; set; }

  /// <summary>
  /// Registrar of the domain.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("registrar")]
  public string? Registrar { get; set; }

  /// <summary>
  /// Mode of the [Zone](#tag/zones).
  /// 
  /// For more information, see [Zone Modes](#tag/zones/zone-modes).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("mode")]
  public string? Mode { get; set; }
}
