//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ZonePrimaryPrimaryNameservers from OpenAPI schema.
/// Schema path: #/components/schemas/ZonePrimaryPrimaryNameservers
/// 
/// Primary nameserver that returns [Zones](#tag/zones) via AXFR.
/// 
/// Must allow queries from and may send NOTIFY queries to [Hetzner&apos;s secondary
/// nameservers](https://docs.hetzner.com/dns-console/dns/general/authoritative-name-servers#secondary-dns-servers-old-name-servers-for-robot-customers).
/// 
/// </summary>
public partial class ZonePrimaryPrimaryNameservers
{
  /// <summary>
  /// Public IPv4 or IPv6 address of the primary nameserver.
  /// 
  /// Must be unique across all primary nameservers of this zone.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("address")]
  public string? Address { get; set; }

  /// <summary>
  /// Port of the primary nameserver.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("port")]
  public int? Port { get; set; }

  /// <summary>
  /// [Transaction signature (TSIG)](https://en.wikipedia.org/wiki/TSIG) key to use
  /// for the zone transfer. Must be base64 encoded.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tsig_key")]
  public string? TsigKey { get; set; }

  /// <summary>
  /// [Transaction signature (TSIG)](https://en.wikipedia.org/wiki/TSIG) algorithm
  /// used to generate the TSIG key.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tsig_algorithm")]
  public string? TsigAlgorithm { get; set; }
}
