//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Cloud.Models;

/// <summary>
/// ZonePrimaryAuthoritativeNameservers from OpenAPI schema.
/// Schema path: #/components/schemas/ZonePrimaryAuthoritativeNameservers
/// </summary>
public partial class ZonePrimaryAuthoritativeNameservers
{
  /// <summary>
  /// Authoritative Hetzner nameservers assigned to this [Zone](#tag/zones).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("assigned")]
  public List<string?>? Assigned { get; set; }

  /// <summary>
  /// Authoritative nameservers currently delegated to by the parent DNS zone.
  /// 
  /// If these don&apos;t match the assigned authoritative nameservers, the DNS zone is currently not being served by Hetzner.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("delegated")]
  public List<string?>? Delegated { get; set; }

  /// <summary>
  /// Point in time (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format) when the DNS zone delegation was last checked.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("delegation_last_check")]
  public DateTimeOffset? DelegationLastCheck { get; set; }

  /// <summary>
  /// Status of the delegation.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("delegation_status")]
  public string? DelegationStatus { get; set; }
}
