//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Certificate Actions operations
/// </summary>
public partial interface ICertificateActionsClient
{
  /// <summary>
  /// List Actions
  /// Operation: GET /certificates/actions
  /// </summary>
  Task<JsonElement> ListAsync(ListCertificatesActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action
  /// Operation: GET /certificates/actions/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Actions for a Certificate
  /// Operation: GET /certificates/{id}/actions
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListCertificateActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Retry Issuance or Renewal
  /// Operation: POST /certificates/{id}/actions/retry
  /// </summary>
  Task<JsonElement> RetryCertificateAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action for a Certificate
  /// Operation: GET /certificates/{id}/actions/{action_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long actionId, CancellationToken cancellationToken = default);

}
