//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Certificates operations
/// </summary>
public partial interface ICertificatesClient
{
  /// <summary>
  /// List Certificates
  /// Operation: GET /certificates
  /// </summary>
  Task<JsonElement> ListAsync(ListCertificatesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Certificate
  /// Operation: POST /certificates
  /// </summary>
  Task<JsonElement> CreateAsync(Apigen.Hetzner.Cloud.Models.CreateCertificateRequest createCertificateRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Certificate
  /// Operation: GET /certificates/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Certificate
  /// Operation: PUT /certificates/{id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, Apigen.Hetzner.Cloud.Models.UpdateCertificateRequest updateCertificateRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Certificate
  /// Operation: DELETE /certificates/{id}
  /// </summary>
  Task DeleteAsync(long id, CancellationToken cancellationToken = default);

}
