//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Data Centers operations
/// </summary>
public partial interface IDataCentersClient
{
  /// <summary>
  /// List Data Centers
  /// Operation: GET /datacenters
  /// </summary>
  Task<JsonElement> ListDatacentersAsync(ListDatacentersRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Data Center
  /// Operation: GET /datacenters/{id}
  /// </summary>
  Task<JsonElement> GetDatacenterAsync(long id, CancellationToken cancellationToken = default);

}
