//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Firewalls operations
/// </summary>
public partial interface IFirewallsClient
{
  /// <summary>
  /// List Firewalls
  /// Operation: GET /firewalls
  /// </summary>
  Task<JsonElement> ListAsync(ListFirewallsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Firewall
  /// Operation: POST /firewalls
  /// </summary>
  Task<JsonElement> CreateAsync(Apigen.Hetzner.Cloud.Models.CreateFirewallRequest createFirewallRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Firewall
  /// Operation: GET /firewalls/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Firewall
  /// Operation: PUT /firewalls/{id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, Apigen.Hetzner.Cloud.Models.UpdateFirewallRequest updateFirewallRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Firewall
  /// Operation: DELETE /firewalls/{id}
  /// </summary>
  Task DeleteAsync(long id, CancellationToken cancellationToken = default);

}
