//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Firewall Actions operations
/// </summary>
public partial interface IFirewallActionsClient
{
  /// <summary>
  /// List Actions
  /// Operation: GET /firewalls/actions
  /// </summary>
  Task<JsonElement> ListAsync(ListFirewallsActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action
  /// Operation: GET /firewalls/actions/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Actions for a Firewall
  /// Operation: GET /firewalls/{id}/actions
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListFirewallActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Apply to Resources
  /// Operation: POST /firewalls/{id}/actions/apply_to_resources
  /// </summary>
  Task<JsonElement> ApplyFirewallToResourcesAsync(long id, Apigen.Hetzner.Cloud.Models.ApplyFirewallToResourcesRequest applyFirewallToResourcesRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Remove from Resources
  /// Operation: POST /firewalls/{id}/actions/remove_from_resources
  /// </summary>
  Task<JsonElement> RemoveFirewallFromResourcesAsync(long id, Apigen.Hetzner.Cloud.Models.RemoveFirewallFromResourcesRequest removeFirewallFromResourcesRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Set Rules
  /// Operation: POST /firewalls/{id}/actions/set_rules
  /// </summary>
  Task<JsonElement> SetFirewallRulesAsync(long id, Apigen.Hetzner.Cloud.Models.SetFirewallRulesRequest setFirewallRulesRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action for a Firewall
  /// Operation: GET /firewalls/{id}/actions/{action_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long actionId, CancellationToken cancellationToken = default);

}
