//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Floating IPs operations
/// </summary>
public partial interface IFloatingIpsClient
{
  /// <summary>
  /// List Floating IPs
  /// Operation: GET /floating_ips
  /// </summary>
  Task<JsonElement> ListFloatingIpsAsync(ListFloatingIpsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Floating IP
  /// Operation: POST /floating_ips
  /// </summary>
  Task<JsonElement> CreateFloatingIpAsync(Apigen.Hetzner.Cloud.Models.CreateFloatingIpRequest createFloatingIpRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Floating IP
  /// Operation: GET /floating_ips/{id}
  /// </summary>
  Task<JsonElement> GetFloatingIpAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Floating IP
  /// Operation: PUT /floating_ips/{id}
  /// </summary>
  Task<JsonElement> UpdateFloatingIpAsync(long id, Apigen.Hetzner.Cloud.Models.UpdateFloatingIpRequest updateFloatingIpRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Floating IP
  /// Operation: DELETE /floating_ips/{id}
  /// </summary>
  Task DeleteFloatingIpAsync(long id, CancellationToken cancellationToken = default);

}
