//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Floating IP Actions operations
/// </summary>
public partial interface IFloatingIpActionsClient
{
  /// <summary>
  /// List Actions
  /// Operation: GET /floating_ips/actions
  /// </summary>
  Task<JsonElement> ListAsync(ListFloatingIpsActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action
  /// Operation: GET /floating_ips/actions/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Actions for a Floating IP
  /// Operation: GET /floating_ips/{id}/actions
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListFloatingIpActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Assign a Floating IP to a Server
  /// Operation: POST /floating_ips/{id}/actions/assign
  /// </summary>
  Task<JsonElement> AssignFloatingIpAsync(long id, Apigen.Hetzner.Cloud.Models.AssignFloatingIpRequest assignFloatingIpRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change reverse DNS records for a Floating IP
  /// Operation: POST /floating_ips/{id}/actions/change_dns_ptr
  /// </summary>
  Task<JsonElement> ChangeFloatingIpDnsPtrAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeFloatingIpDnsPtrRequest changeFloatingIpDnsPtrRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change Floating IP Protection
  /// Operation: POST /floating_ips/{id}/actions/change_protection
  /// </summary>
  Task<JsonElement> ChangeFloatingIpProtectionAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeFloatingIpProtectionRequest changeFloatingIpProtectionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Unassign a Floating IP
  /// Operation: POST /floating_ips/{id}/actions/unassign
  /// </summary>
  Task<JsonElement> UnassignFloatingIpAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action for a Floating IP
  /// Operation: GET /floating_ips/{id}/actions/{action_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long actionId, CancellationToken cancellationToken = default);

}
