//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Image Actions operations
/// </summary>
public partial interface IImageActionsClient
{
  /// <summary>
  /// List Actions
  /// Operation: GET /images/actions
  /// </summary>
  Task<JsonElement> ListAsync(ListImagesActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action
  /// Operation: GET /images/actions/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Actions for an Image
  /// Operation: GET /images/{id}/actions
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListImageActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change Image Protection
  /// Operation: POST /images/{id}/actions/change_protection
  /// </summary>
  Task<JsonElement> ChangeImageProtectionAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeImageProtectionRequest changeImageProtectionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action for an Image
  /// Operation: GET /images/{id}/actions/{action_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long actionId, CancellationToken cancellationToken = default);

}
