//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Images operations
/// </summary>
public partial interface IImagesClient
{
  /// <summary>
  /// List Images
  /// Operation: GET /images
  /// </summary>
  Task<JsonElement> ListAsync(ListImagesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Image
  /// Operation: GET /images/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update an Image
  /// Operation: PUT /images/{id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, Apigen.Hetzner.Cloud.Models.UpdateImageRequest updateImageRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete an Image
  /// Operation: DELETE /images/{id}
  /// </summary>
  Task DeleteAsync(long id, CancellationToken cancellationToken = default);

}
