//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Load Balancers operations
/// </summary>
public partial interface ILoadBalancersClient
{
  /// <summary>
  /// List Load Balancers
  /// Operation: GET /load_balancers
  /// </summary>
  Task<JsonElement> ListAsync(ListLoadBalancersRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Load Balancer
  /// Operation: POST /load_balancers
  /// </summary>
  Task<JsonElement> CreateAsync(Apigen.Hetzner.Cloud.Models.CreateLoadBalancerRequest createLoadBalancerRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Load Balancer
  /// Operation: GET /load_balancers/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Load Balancer
  /// Operation: PUT /load_balancers/{id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, Apigen.Hetzner.Cloud.Models.UpdateLoadBalancerRequest updateLoadBalancerRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Load Balancer
  /// Operation: DELETE /load_balancers/{id}
  /// </summary>
  Task DeleteAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Metrics for a LoadBalancer
  /// Operation: GET /load_balancers/{id}/metrics
  /// </summary>
  Task<JsonElement> GetLoadBalancerMetricsAsync(long id, GetLoadBalancerMetricsRequest? request = null, CancellationToken cancellationToken = default);

}
