//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Load Balancer Actions operations
/// </summary>
public partial interface ILoadBalancerActionsClient
{
  /// <summary>
  /// List Actions
  /// Operation: GET /load_balancers/actions
  /// </summary>
  Task<JsonElement> ListAsync(ListLoadBalancersActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action
  /// Operation: GET /load_balancers/actions/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Actions for a Load Balancer
  /// Operation: GET /load_balancers/{id}/actions
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListLoadBalancerActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add Service
  /// Operation: POST /load_balancers/{id}/actions/add_service
  /// </summary>
  Task<JsonElement> AddLoadBalancerServiceAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add Target
  /// Operation: POST /load_balancers/{id}/actions/add_target
  /// </summary>
  Task<JsonElement> AddLoadBalancerTargetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Attach a Load Balancer to a Network
  /// Operation: POST /load_balancers/{id}/actions/attach_to_network
  /// </summary>
  Task<JsonElement> AttachLoadBalancerToNetworkAsync(long id, Apigen.Hetzner.Cloud.Models.AttachLoadBalancerToNetworkRequest attachLoadBalancerToNetworkRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change Algorithm
  /// Operation: POST /load_balancers/{id}/actions/change_algorithm
  /// </summary>
  Task<JsonElement> ChangeLoadBalancerAlgorithmAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeLoadBalancerAlgorithmRequest changeLoadBalancerAlgorithmRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change reverse DNS entry for this Load Balancer
  /// Operation: POST /load_balancers/{id}/actions/change_dns_ptr
  /// </summary>
  Task<JsonElement> ChangeLoadBalancerDnsPtrAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeLoadBalancerDnsPtrRequest changeLoadBalancerDnsPtrRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change Load Balancer Protection
  /// Operation: POST /load_balancers/{id}/actions/change_protection
  /// </summary>
  Task<JsonElement> ChangeLoadBalancerProtectionAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeLoadBalancerProtectionRequest changeLoadBalancerProtectionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change the Type of a Load Balancer
  /// Operation: POST /load_balancers/{id}/actions/change_type
  /// </summary>
  Task<JsonElement> ChangeLoadBalancerTypeAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeLoadBalancerTypeRequest changeLoadBalancerTypeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete Service
  /// Operation: POST /load_balancers/{id}/actions/delete_service
  /// </summary>
  Task<JsonElement> DeleteLoadBalancerServiceAsync(long id, Apigen.Hetzner.Cloud.Models.DeleteLoadBalancerServiceRequest deleteLoadBalancerServiceRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Detach a Load Balancer from a Network
  /// Operation: POST /load_balancers/{id}/actions/detach_from_network
  /// </summary>
  Task<JsonElement> DetachLoadBalancerFromNetworkAsync(long id, Apigen.Hetzner.Cloud.Models.DetachLoadBalancerFromNetworkRequest detachLoadBalancerFromNetworkRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Disable the public interface of a Load Balancer
  /// Operation: POST /load_balancers/{id}/actions/disable_public_interface
  /// </summary>
  Task<JsonElement> DisableLoadBalancerPublicInterfaceAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Enable the public interface of a Load Balancer
  /// Operation: POST /load_balancers/{id}/actions/enable_public_interface
  /// </summary>
  Task<JsonElement> EnableLoadBalancerPublicInterfaceAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Remove Target
  /// Operation: POST /load_balancers/{id}/actions/remove_target
  /// </summary>
  Task<JsonElement> RemoveLoadBalancerTargetAsync(long id, Apigen.Hetzner.Cloud.Models.RemoveLoadBalancerTargetRequest removeLoadBalancerTargetRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Service
  /// Operation: POST /load_balancers/{id}/actions/update_service
  /// </summary>
  Task<JsonElement> UpdateLoadBalancerServiceAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action for a Load Balancer
  /// Operation: GET /load_balancers/{id}/actions/{action_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long actionId, CancellationToken cancellationToken = default);

}
