//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Load Balancer Types operations
/// </summary>
public partial interface ILoadBalancerTypesClient
{
  /// <summary>
  /// List Load Balancer Types
  /// Operation: GET /load_balancer_types
  /// </summary>
  Task<JsonElement> ListAsync(ListLoadBalancerTypesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Load Balancer Type
  /// Operation: GET /load_balancer_types/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

}
