//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Networks operations
/// </summary>
public partial interface INetworksClient
{
  /// <summary>
  /// List Networks
  /// Operation: GET /networks
  /// </summary>
  Task<JsonElement> ListAsync(ListNetworksRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Network
  /// Operation: POST /networks
  /// </summary>
  Task<JsonElement> CreateAsync(Apigen.Hetzner.Cloud.Models.CreateNetworkRequest createNetworkRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Network
  /// Operation: GET /networks/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Network
  /// Operation: PUT /networks/{id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, Apigen.Hetzner.Cloud.Models.UpdateNetworkRequest updateNetworkRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Network
  /// Operation: DELETE /networks/{id}
  /// </summary>
  Task DeleteAsync(long id, CancellationToken cancellationToken = default);

}
