//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Network Actions operations
/// </summary>
public partial interface INetworkActionsClient
{
  /// <summary>
  /// List Actions
  /// Operation: GET /networks/actions
  /// </summary>
  Task<JsonElement> ListAsync(ListNetworksActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action
  /// Operation: GET /networks/actions/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Actions for a Network
  /// Operation: GET /networks/{id}/actions
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListNetworkActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add a route to a Network
  /// Operation: POST /networks/{id}/actions/add_route
  /// </summary>
  Task<JsonElement> AddNetworkRouteAsync(long id, Apigen.Hetzner.Cloud.Models.AddNetworkRouteRequest addNetworkRouteRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add a subnet to a Network
  /// Operation: POST /networks/{id}/actions/add_subnet
  /// </summary>
  Task<JsonElement> AddNetworkSubnetAsync(long id, Apigen.Hetzner.Cloud.Models.AddNetworkSubnetRequest addNetworkSubnetRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change IP range of a Network
  /// Operation: POST /networks/{id}/actions/change_ip_range
  /// </summary>
  Task<JsonElement> ChangeNetworkIpRangeAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeNetworkIpRangeRequest changeNetworkIpRangeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change Network Protection
  /// Operation: POST /networks/{id}/actions/change_protection
  /// </summary>
  Task<JsonElement> ChangeNetworkProtectionAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeNetworkProtectionRequest changeNetworkProtectionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a route from a Network
  /// Operation: POST /networks/{id}/actions/delete_route
  /// </summary>
  Task<JsonElement> DeleteNetworkRouteAsync(long id, Apigen.Hetzner.Cloud.Models.DeleteNetworkRouteRequest deleteNetworkRouteRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a subnet from a Network
  /// Operation: POST /networks/{id}/actions/delete_subnet
  /// </summary>
  Task<JsonElement> DeleteNetworkSubnetAsync(long id, Apigen.Hetzner.Cloud.Models.DeleteNetworkSubnetRequest deleteNetworkSubnetRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action for a Network
  /// Operation: GET /networks/{id}/actions/{action_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long actionId, CancellationToken cancellationToken = default);

}
