//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Placement Groups operations
/// </summary>
public partial interface IPlacementGroupsClient
{
  /// <summary>
  /// List Placement Groups
  /// Operation: GET /placement_groups
  /// </summary>
  Task<JsonElement> ListAsync(ListPlacementGroupsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a PlacementGroup
  /// Operation: POST /placement_groups
  /// </summary>
  Task<JsonElement> CreateAsync(Apigen.Hetzner.Cloud.Models.CreatePlacementGroupRequest createPlacementGroupRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a PlacementGroup
  /// Operation: GET /placement_groups/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a PlacementGroup
  /// Operation: PUT /placement_groups/{id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, Apigen.Hetzner.Cloud.Models.UpdatePlacementGroupRequest updatePlacementGroupRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a PlacementGroup
  /// Operation: DELETE /placement_groups/{id}
  /// </summary>
  Task DeleteAsync(long id, CancellationToken cancellationToken = default);

}
