//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Primary IP Actions operations
/// </summary>
public partial interface IPrimaryIpActionsClient
{
  /// <summary>
  /// List Actions
  /// Operation: GET /primary_ips/actions
  /// </summary>
  Task<JsonElement> ListAsync(ListPrimaryIpsActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action
  /// Operation: GET /primary_ips/actions/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Actions for a Primary IP
  /// Operation: GET /primary_ips/{id}/actions
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListPrimaryIpActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action for a Primary IP
  /// Operation: GET /primary_ips/{id}/actions/{action_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long actionId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Assign a Primary IP to a resource
  /// Operation: POST /primary_ips/{id}/actions/assign
  /// </summary>
  Task<JsonElement> AssignPrimaryIpAsync(long id, Apigen.Hetzner.Cloud.Models.AssignPrimaryIpRequest assignPrimaryIpRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change reverse DNS records for a Primary IP
  /// Operation: POST /primary_ips/{id}/actions/change_dns_ptr
  /// </summary>
  Task<JsonElement> ChangePrimaryIpDnsPtrAsync(long id, Apigen.Hetzner.Cloud.Models.ChangePrimaryIpDnsPtrRequest changePrimaryIpDnsPtrRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change Primary IP Protection
  /// Operation: POST /primary_ips/{id}/actions/change_protection
  /// </summary>
  Task<JsonElement> ChangePrimaryIpProtectionAsync(long id, Apigen.Hetzner.Cloud.Models.ChangePrimaryIpProtectionRequest changePrimaryIpProtectionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Unassign a Primary IP from a resource
  /// Operation: POST /primary_ips/{id}/actions/unassign
  /// </summary>
  Task<JsonElement> UnassignPrimaryIpAsync(long id, CancellationToken cancellationToken = default);

}
