//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Primary IPs operations
/// </summary>
public partial interface IPrimaryIpsClient
{
  /// <summary>
  /// List Primary IPs
  /// Operation: GET /primary_ips
  /// </summary>
  Task<JsonElement> ListPrimaryIpsAsync(ListPrimaryIpsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Primary IP
  /// Operation: POST /primary_ips
  /// </summary>
  Task<JsonElement> CreatePrimaryIpAsync(Apigen.Hetzner.Cloud.Models.CreatePrimaryIpRequest createPrimaryIpRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Primary IP
  /// Operation: GET /primary_ips/{id}
  /// </summary>
  Task<JsonElement> GetPrimaryIpAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Primary IP
  /// Operation: PUT /primary_ips/{id}
  /// </summary>
  Task<JsonElement> UpdatePrimaryIpAsync(long id, Apigen.Hetzner.Cloud.Models.UpdatePrimaryIpRequest updatePrimaryIpRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Primary IP
  /// Operation: DELETE /primary_ips/{id}
  /// </summary>
  Task DeletePrimaryIpAsync(long id, CancellationToken cancellationToken = default);

}
