//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Servers operations
/// </summary>
public partial interface IServersClient
{
  /// <summary>
  /// List Servers
  /// Operation: GET /servers
  /// </summary>
  Task<JsonElement> ListAsync(ListServersRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Server
  /// Operation: POST /servers
  /// </summary>
  Task<JsonElement> CreateAsync(Apigen.Hetzner.Cloud.Models.CreateServerRequest createServerRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Server
  /// Operation: GET /servers/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Server
  /// Operation: PUT /servers/{id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, Apigen.Hetzner.Cloud.Models.UpdateServerRequest updateServerRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Server
  /// Operation: DELETE /servers/{id}
  /// </summary>
  Task<JsonElement> DeleteAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get Metrics for a Server
  /// Operation: GET /servers/{id}/metrics
  /// </summary>
  Task<JsonElement> GetServerMetricsAsync(long id, GetServerMetricsRequest? request = null, CancellationToken cancellationToken = default);

}
