//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for SSH Keys operations
/// </summary>
public partial interface ISshKeysClient
{
  /// <summary>
  /// List SSH keys
  /// Operation: GET /ssh_keys
  /// </summary>
  Task<JsonElement> ListAsync(ListSshKeysRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create an SSH key
  /// Operation: POST /ssh_keys
  /// </summary>
  Task<JsonElement> CreateAsync(Apigen.Hetzner.Cloud.Models.CreateSshKeyRequest createSshKeyRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a SSH key
  /// Operation: GET /ssh_keys/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update an SSH key
  /// Operation: PUT /ssh_keys/{id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, Apigen.Hetzner.Cloud.Models.UpdateSshKeyRequest updateSshKeyRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete an SSH key
  /// Operation: DELETE /ssh_keys/{id}
  /// </summary>
  Task DeleteAsync(long id, CancellationToken cancellationToken = default);

}
