//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Volumes operations
/// </summary>
public partial interface IVolumesClient
{
  /// <summary>
  /// List Volumes
  /// Operation: GET /volumes
  /// </summary>
  Task<JsonElement> ListAsync(ListVolumesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Volume
  /// Operation: POST /volumes
  /// </summary>
  Task<JsonElement> CreateAsync(Apigen.Hetzner.Cloud.Models.CreateVolumeRequest createVolumeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Volume
  /// Operation: GET /volumes/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Volume
  /// Operation: PUT /volumes/{id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, Apigen.Hetzner.Cloud.Models.UpdateVolumeRequest updateVolumeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Volume
  /// Operation: DELETE /volumes/{id}
  /// </summary>
  Task DeleteAsync(long id, CancellationToken cancellationToken = default);

}
