//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Volume Actions operations
/// </summary>
public partial interface IVolumeActionsClient
{
  /// <summary>
  /// List Actions
  /// Operation: GET /volumes/actions
  /// </summary>
  Task<JsonElement> ListAsync(ListVolumesActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action
  /// Operation: GET /volumes/actions/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Actions for a Volume
  /// Operation: GET /volumes/{id}/actions
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListVolumeActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Attach Volume to a Server
  /// Operation: POST /volumes/{id}/actions/attach
  /// </summary>
  Task<JsonElement> AttachVolumeAsync(long id, Apigen.Hetzner.Cloud.Models.AttachVolumeRequest attachVolumeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change Volume Protection
  /// Operation: POST /volumes/{id}/actions/change_protection
  /// </summary>
  Task<JsonElement> ChangeVolumeProtectionAsync(long id, Apigen.Hetzner.Cloud.Models.ChangeVolumeProtectionRequest changeVolumeProtectionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Detach Volume
  /// Operation: POST /volumes/{id}/actions/detach
  /// </summary>
  Task<JsonElement> DetachVolumeAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Resize Volume
  /// Operation: POST /volumes/{id}/actions/resize
  /// </summary>
  Task<JsonElement> ResizeVolumeAsync(long id, Apigen.Hetzner.Cloud.Models.ResizeVolumeRequest resizeVolumeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action for a Volume
  /// Operation: GET /volumes/{id}/actions/{action_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long actionId, CancellationToken cancellationToken = default);

}
