//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Cloud.Models;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Interface for Zone RRSets operations
/// </summary>
public partial interface IZoneRRSetsClient
{
  /// <summary>
  /// List RRSets
  /// Operation: GET /zones/{id_or_name}/rrsets
  /// </summary>
  Task<JsonElement> ListZoneRrsetsAsync(string idOrName, ListZoneRrsetsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create an RRSet
  /// Operation: POST /zones/{id_or_name}/rrsets
  /// </summary>
  Task<JsonElement> CreateZoneRrsetAsync(string idOrName, Apigen.Hetzner.Cloud.Models.CreateZoneRrsetRequest createZoneRrsetRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an RRSet
  /// Operation: GET /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}
  /// </summary>
  Task<JsonElement> GetZoneRrsetAsync(string idOrName, string rrName, string rrType, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update an RRSet
  /// Operation: PUT /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}
  /// </summary>
  Task<JsonElement> UpdateZoneRrsetAsync(string idOrName, string rrName, string rrType, Apigen.Hetzner.Cloud.Models.UpdateZoneRrsetRequest updateZoneRrsetRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete an RRSet
  /// Operation: DELETE /zones/{id_or_name}/rrsets/{rr_name}/{rr_type}
  /// </summary>
  Task<JsonElement> DeleteZoneRrsetAsync(string idOrName, string rrName, string rrType, CancellationToken cancellationToken = default);

}
