//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
// <auto-generated />
using System.Text.Json;
using System.Text.Json.Serialization;
using Apigen.Hetzner.Robot.Models;

#nullable enable

namespace Apigen.Hetzner.Robot;

/// <summary>
/// Internal JSON serialization configuration.
/// </summary>
internal static class JsonConfig
{
  /// <summary>
  /// Default JSON serializer options for all API operations.
  /// </summary>
  internal static readonly JsonSerializerOptions Default = CreateOptions();

  private static JsonSerializerOptions CreateOptions()
  {
    JsonSerializerOptions options = new()
    {
      DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };
    options.Converters.Add(new SmartEnumConverterFactory());
    return options;
  }
}
