//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Robot.Models;

#nullable enable

namespace Apigen.Hetzner.Robot;

/// <summary>
/// Interface for failover operations
/// </summary>
public partial interface IFailoverClient
{
  /// <summary>
  /// Get failover
  /// Operation: GET /failover/{ip}
  /// </summary>
  Task<FailoverGetResponse> GetAsync(string ip, FailoverGetRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Route failover
  /// Operation: POST /failover/{ip}
  /// </summary>
  Task<FailoverRouteResponse> RouteAsync(string ip, Apigen.Hetzner.Robot.Models.FailoverRouteRequest failoverRouteRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete failover routing
  /// Operation: DELETE /failover/{ip}
  /// </summary>
  Task<FailoverDeleteResponse> DeleteAsync(string ip, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get failover (collection)
  /// Operation: GET /failover
  /// </summary>
  Task<List<FailoverGetAllResponse>> ListAsync(FailoverGetAllRequest? request = null, CancellationToken cancellationToken = default);

}
