//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Robot.Models;

#nullable enable

namespace Apigen.Hetzner.Robot;

/// <summary>
/// Interface for subnet operations
/// </summary>
public partial interface ISubnetClient
{
  /// <summary>
  /// Get all subnets of specific server
  /// Operation: GET /subnet
  /// </summary>
  Task<List<SubnetGetByServerIpResponse>> ListAsync(SubnetGetByServerIpRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get subnet
  /// Operation: GET /subnet/{ip}
  /// </summary>
  Task<SubnetGetResponse> GetAsync(string ip, CancellationToken cancellationToken = default);

  /// <summary>
  /// Set traffic warning limits for subnet
  /// Operation: POST /subnet/{ip}
  /// </summary>
  Task<SubnetSetTrafficWarningLimitsResponse> SetTrafficWarningLimitsAsync(string ip, Apigen.Hetzner.Robot.Models.SubnetSetTrafficWarningLimitsRequest subnetSetTrafficWarningLimitsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get the mac address of a ipv6 subnet
  /// Operation: GET /subnet/{ip}/mac
  /// </summary>
  Task<SubnetMacGetResponse> MacGetAsync(string ip, CancellationToken cancellationToken = default);

  /// <summary>
  /// Set the mac address of a ipv6 subnet
  /// Operation: PUT /subnet/{ip}/mac
  /// </summary>
  Task<SubnetMacSetResponse> MacSetAsync(string ip, Apigen.Hetzner.Robot.Models.SubnetMacSetRequest subnetMacSetRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Reset the mac address of a ipv6 subnet to the
  /// Operation: DELETE /subnet/{ip}/mac
  /// </summary>
  Task<SubnetMacResetResponse> MacResetAsync(string ip, CancellationToken cancellationToken = default);

}
