//
// <auto-generated>
// Hetzner Robot Webservice Client - Auto-generated from reverse-engineered OpenAPI spec
//
// Generated by: ApiGenerator
// Source: specs/robot.spec.yaml
// API: Hetzner Robot Webservice
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Robot.Models;

#nullable enable

namespace Apigen.Hetzner.Robot;

/// <summary>
/// Interface for wol operations
/// </summary>
public partial interface IWolClient
{
  /// <summary>
  /// Get Wake On Lan data
  /// Operation: GET /wol/{server_number}
  /// </summary>
  Task<WolGetResponse> GetAsync(string serverNumber, CancellationToken cancellationToken = default);

  /// <summary>
  /// Send Wake On Lan packet to server
  /// Operation: POST /wol/{server_number}
  /// </summary>
  Task<WolSendResponse> SendAsync(string serverNumber, CancellationToken cancellationToken = default);

}
