//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Api.Models;

#nullable enable

namespace Apigen.Hetzner.Api;

/// <summary>
/// Interface for Storage Box Snapshots operations
/// </summary>
public partial interface IStorageBoxSnapshotsClient
{
  /// <summary>
  /// List Snapshots
  /// Operation: GET /storage_boxes/{id}/snapshots
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListStorageBoxSnapshotsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Snapshot
  /// Operation: POST /storage_boxes/{id}/snapshots
  /// </summary>
  Task<JsonElement> CreateAsync(long id, Apigen.Hetzner.Api.Models.CreateStorageBoxSnapshotRequest createStorageBoxSnapshotRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Snapshot
  /// Operation: GET /storage_boxes/{id}/snapshots/{snapshot_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long snapshotId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Snapshot
  /// Operation: PUT /storage_boxes/{id}/snapshots/{snapshot_id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, long snapshotId, Apigen.Hetzner.Api.Models.UpdateStorageBoxSnapshotRequest updateStorageBoxSnapshotRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Snapshot
  /// Operation: DELETE /storage_boxes/{id}/snapshots/{snapshot_id}
  /// </summary>
  Task<JsonElement> DeleteAsync(long id, long snapshotId, CancellationToken cancellationToken = default);

}
