//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Api.Models;

#nullable enable

namespace Apigen.Hetzner.Api;

/// <summary>
/// Interface for Storage Box Types operations
/// </summary>
public partial interface IStorageBoxTypesClient
{
  /// <summary>
  /// List Storage Box Types
  /// Operation: GET /storage_box_types
  /// </summary>
  Task<JsonElement> ListAsync(ListStorageBoxTypesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Storage Box Type
  /// Operation: GET /storage_box_types/{id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, CancellationToken cancellationToken = default);

}
