//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Api.Models;

#nullable enable

namespace Apigen.Hetzner.Api;

/// <summary>
/// Interface for Storage Boxes operations
/// </summary>
public partial interface IStorageBoxesClient
{
  /// <summary>
  /// List Storage Boxes
  /// Operation: GET /storage_boxes
  /// </summary>
  Task<JsonElement> ListAsync(ListStorageBoxesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Storage Box
  /// Operation: POST /storage_boxes
  /// </summary>
  Task<JsonElement> CreateStorageBoxAsync(Apigen.Hetzner.Api.Models.CreateStorageBoxRequest createStorageBoxRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Storage Box
  /// Operation: GET /storage_boxes/{id}
  /// </summary>
  Task<JsonElement> GetStorageBoxAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Storage Box
  /// Operation: PUT /storage_boxes/{id}
  /// </summary>
  Task<JsonElement> UpdateStorageBoxAsync(long id, Apigen.Hetzner.Api.Models.UpdateStorageBoxRequest updateStorageBoxRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Storage Box
  /// Operation: DELETE /storage_boxes/{id}
  /// </summary>
  Task<JsonElement> DeleteStorageBoxAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List folders of a Storage Box
  /// Operation: GET /storage_boxes/{id}/folders
  /// </summary>
  Task<JsonElement> ListStorageBoxFoldersAsync(long id, ListStorageBoxFoldersRequest? request = null, CancellationToken cancellationToken = default);

}
