//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Api.Models;

#nullable enable

namespace Apigen.Hetzner.Api;

/// <summary>
/// Interface for Storage Box Actions operations
/// </summary>
public partial interface IStorageBoxActionsClient
{
  /// <summary>
  /// List Actions
  /// Operation: GET /storage_boxes/actions
  /// </summary>
  Task<JsonElement> ListStorageBoxesActionsAsync(ListStorageBoxesActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action
  /// Operation: GET /storage_boxes/actions/{id}
  /// </summary>
  Task<JsonElement> GetStorageBoxesActionAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// List Actions for a Storage Box
  /// Operation: GET /storage_boxes/{id}/actions
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListStorageBoxActionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get an Action for a Storage Box
  /// Operation: GET /storage_boxes/{id}/actions/{action_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long actionId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change Protection
  /// Operation: POST /storage_boxes/{id}/actions/change_protection
  /// </summary>
  Task<JsonElement> ChangeStorageBoxProtectionAsync(long id, Apigen.Hetzner.Api.Models.ChangeStorageBoxProtectionRequest changeStorageBoxProtectionRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Change Type
  /// Operation: POST /storage_boxes/{id}/actions/change_type
  /// </summary>
  Task<JsonElement> ChangeStorageBoxTypeAsync(long id, Apigen.Hetzner.Api.Models.ChangeStorageBoxTypeRequest changeStorageBoxTypeRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Reset Password
  /// Operation: POST /storage_boxes/{id}/actions/reset_password
  /// </summary>
  Task<JsonElement> ResetStorageBoxPasswordAsync(long id, Apigen.Hetzner.Api.Models.ResetStorageBoxPasswordRequest resetStorageBoxPasswordRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Access Settings
  /// Operation: POST /storage_boxes/{id}/actions/update_access_settings
  /// </summary>
  Task<JsonElement> UpdateStorageBoxAccessSettingsAsync(long id, Apigen.Hetzner.Api.Models.UpdateStorageBoxAccessSettingsRequest updateStorageBoxAccessSettingsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Rollback Snapshot
  /// Operation: POST /storage_boxes/{id}/actions/rollback_snapshot
  /// </summary>
  Task<JsonElement> RollbackStorageBoxSnapshotAsync(long id, Apigen.Hetzner.Api.Models.RollbackStorageBoxSnapshotRequest rollbackStorageBoxSnapshotRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Disable Snapshot Plan
  /// Operation: POST /storage_boxes/{id}/actions/disable_snapshot_plan
  /// </summary>
  Task<JsonElement> DisableStorageBoxSnapshotPlanAsync(long id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Enable Snapshot Plan
  /// Operation: POST /storage_boxes/{id}/actions/enable_snapshot_plan
  /// </summary>
  Task<JsonElement> EnableStorageBoxSnapshotPlanAsync(long id, Apigen.Hetzner.Api.Models.EnableStorageBoxSnapshotPlanRequest enableStorageBoxSnapshotPlanRequest, CancellationToken cancellationToken = default);

}
