//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Api.Models;

#nullable enable

namespace Apigen.Hetzner.Api;

/// <summary>
/// Interface for Storage Box Subaccounts operations
/// </summary>
public partial interface IStorageBoxSubaccountsClient
{
  /// <summary>
  /// List Subaccounts
  /// Operation: GET /storage_boxes/{id}/subaccounts
  /// </summary>
  Task<JsonElement> ListAsync(long id, ListStorageBoxSubaccountsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a Subaccount
  /// Operation: POST /storage_boxes/{id}/subaccounts
  /// </summary>
  Task<JsonElement> CreateAsync(long id, Apigen.Hetzner.Api.Models.CreateStorageBoxSubaccountRequest createStorageBoxSubaccountRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get a Subaccount
  /// Operation: GET /storage_boxes/{id}/subaccounts/{subaccount_id}
  /// </summary>
  Task<JsonElement> GetAsync(long id, long subaccountId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update a Subaccount
  /// Operation: PUT /storage_boxes/{id}/subaccounts/{subaccount_id}
  /// </summary>
  Task<JsonElement> UpdateAsync(long id, long subaccountId, Apigen.Hetzner.Api.Models.UpdateStorageBoxSubaccountRequest updateStorageBoxSubaccountRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a Subaccount
  /// Operation: DELETE /storage_boxes/{id}/subaccounts/{subaccount_id}
  /// </summary>
  Task<JsonElement> DeleteAsync(long id, long subaccountId, CancellationToken cancellationToken = default);

}
