//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Hetzner.Api.Models;

#nullable enable

namespace Apigen.Hetzner.Api;

/// <summary>
/// Interface for Storage Box Subaccount Actions operations
/// </summary>
public partial interface IStorageBoxSubaccountActionsClient
{
  /// <summary>
  /// Change Home Directory
  /// Operation: POST /storage_boxes/{id}/subaccounts/{subaccount_id}/actions/change_home_directory
  /// </summary>
  Task<JsonElement> ChangeStorageBoxSubaccountHomeDirectoryAsync(long id, long subaccountId, Apigen.Hetzner.Api.Models.ChangeStorageBoxSubaccountHomeDirectoryRequest changeStorageBoxSubaccountHomeDirectoryRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Reset Password
  /// Operation: POST /storage_boxes/{id}/subaccounts/{subaccount_id}/actions/reset_subaccount_password
  /// </summary>
  Task<JsonElement> ResetStorageBoxSubaccountPasswordAsync(long id, long subaccountId, Apigen.Hetzner.Api.Models.ResetStorageBoxSubaccountPasswordRequest resetStorageBoxSubaccountPasswordRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update Access Settings
  /// Operation: POST /storage_boxes/{id}/subaccounts/{subaccount_id}/actions/update_access_settings
  /// </summary>
  Task<JsonElement> UpdateStorageBoxSubaccountAccessSettingsAsync(long id, long subaccountId, Apigen.Hetzner.Api.Models.UpdateStorageBoxSubaccountAccessSettingsRequest updateStorageBoxSubaccountAccessSettingsRequest, CancellationToken cancellationToken = default);

}
