//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Api.Models;

/// <summary>
/// ChangeStorageBoxProtectionRequest (generated from inline request body).
/// Source: POST /storage_boxes/{id}/actions/change_protection (requestBody)
/// 
/// Protection configuration for the Resource.
/// </summary>
public partial class ChangeStorageBoxProtectionRequest
{
  /// <summary>
  /// Prevent the Resource from being deleted.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("delete")]
  public bool? Delete { get; set; }
}
