//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Api.Models;

/// <summary>
/// ChangeStorageBoxSubaccountHomeDirectoryRequest (generated from inline request body).
/// Source: POST /storage_boxes/{id}/subaccounts/{subaccount_id}/actions/change_home_directory (requestBody)
/// </summary>
public partial class ChangeStorageBoxSubaccountHomeDirectoryRequest
{
  /// <summary>
  /// Home directory of the [Storage Box Subaccount](#tag/storage-box-subaccounts).
  /// 
  /// The directory will be created if it doesn&apos;t exist yet.
  /// 
  /// </summary>
  [Required]
  [MinLength(1)]
  [MaxLength(999)]
  [RegularExpression(@"^[a-zA-Z0-9 ./_-]+$")]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("home_directory")]
  public string? HomeDirectory { get; set; }
}
