//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Api.Models;

/// <summary>
/// ChangeStorageBoxTypeRequest (generated from inline request body).
/// Source: POST /storage_boxes/{id}/actions/change_type (requestBody)
/// </summary>
public partial class ChangeStorageBoxTypeRequest
{
  /// <summary>
  /// ID or Name of the [Storage Box Type](#tag/storage-box-types).
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("storage_box_type")]
  public string? StorageBoxType { get; set; }
}
