//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Api.Models;

/// <summary>
/// CreateStorageBoxSubaccountRequest (generated from inline request body).
/// Source: POST /storage_boxes/{id}/subaccounts (requestBody)
/// </summary>
public partial class CreateStorageBoxSubaccountRequest
{
  /// <summary>
  /// Home directory of the [Storage Box Subaccount](#tag/storage-box-subaccounts).
  /// 
  /// The directory will be created if it doesn&apos;t exist yet.
  /// 
  /// </summary>
  [Required]
  [MinLength(1)]
  [MaxLength(999)]
  [RegularExpression(@"^[a-zA-Z0-9 ./_-]+$")]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("home_directory")]
  public string? HomeDirectory { get; set; }

  /// <summary>
  /// Password of the [Storage Box Subaccount](#tag/storage-box-subaccounts).
  /// 
  /// For more details, see the [Storage Boxes password policy](#tag/storage-boxes/password-policy).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("access_settings")]
  public object? AccessSettings { get; set; }

  /// <summary>
  /// Name of the [Storage Box Subaccount](#tag/storage-box-subaccounts).
  /// 
  /// Defaults to the [Storage Box Subaccount](#tag/storage-box-subaccounts) username.
  /// 
  /// </summary>
  [MinLength(1)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// A description of [Storage Box Subaccount](#tag/storage-box-subaccounts).
  /// 
  /// </summary>
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }
}
