//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Api.Models;

/// <summary>
/// CreateStorageBoxRequestAccessSettings from OpenAPI schema.
/// Schema path: #/components/schemas/CreateStorageBoxRequestAccessSettings
/// 
/// Access settings of the [Storage Box](#tag/storage-boxes).
/// </summary>
public partial class CreateStorageBoxRequestAccessSettings
{
  /// <summary>
  /// Whether access from outside the Hetzner network is allowed.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reachable_externally")]
  public bool? ReachableExternally { get; set; }

  /// <summary>
  /// Whether the Samba subsystem is enabled.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("samba_enabled")]
  public bool? SambaEnabled { get; set; }

  /// <summary>
  /// Whether the SSH subsystem is enabled.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ssh_enabled")]
  public bool? SshEnabled { get; set; }

  /// <summary>
  /// Whether the WebDAV subsystem is enabled.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("webdav_enabled")]
  public bool? WebdavEnabled { get; set; }

  /// <summary>
  /// Whether the ZFS snapshot folder is visible.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("zfs_enabled")]
  public bool? ZfsEnabled { get; set; }
}
