//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Api.Models;

/// <summary>
/// EnableStorageBoxSnapshotPlanRequest (generated from inline request body).
/// Source: POST /storage_boxes/{id}/actions/enable_snapshot_plan (requestBody)
/// </summary>
public partial class EnableStorageBoxSnapshotPlanRequest
{
  /// <summary>
  /// Maximum amount of Snapshots that will be created by this Snapshot Plan.
  /// 
  /// Older Snapshots will be deleted.
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("max_snapshots")]
  public int MaxSnapshots { get; set; }

  /// <summary>
  /// Minute when the Snapshot Plan is executed (UTC).
  /// 
  /// </summary>
  [Required]
  [Range(0, 59)]
  [System.Text.Json.Serialization.JsonPropertyName("minute")]
  public int Minute { get; set; }

  /// <summary>
  /// Hour when the Snapshot Plan is executed (UTC).
  /// 
  /// </summary>
  [Required]
  [Range(0, 23)]
  [System.Text.Json.Serialization.JsonPropertyName("hour")]
  public int Hour { get; set; }

  /// <summary>
  /// Day of the week when the Snapshot Plan is executed.
  /// 
  /// Starts at 1 for Monday til 7 for Sunday. Null means every day.
  /// 
  /// </summary>
  [Range(1, 7)]
  [System.Text.Json.Serialization.JsonPropertyName("day_of_week")]
  public int? DayOfWeek { get; set; }

  /// <summary>
  /// Day of the month when the Snapshot Plan is executed.
  /// 
  /// Null means every day.
  /// 
  /// </summary>
  [Range(1, 31)]
  [System.Text.Json.Serialization.JsonPropertyName("day_of_month")]
  public int? DayOfMonth { get; set; }
}
