//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Api.Models;

/// <summary>
/// ResetStorageBoxSubaccountPasswordRequest (generated from inline request body).
/// Source: POST /storage_boxes/{id}/subaccounts/{subaccount_id}/actions/reset_subaccount_password (requestBody)
/// </summary>
public partial class ResetStorageBoxSubaccountPasswordRequest
{
  /// <summary>
  /// Password of the [Storage Box Subaccount](#tag/storage-box-subaccounts).
  /// 
  /// For more details, see the [Storage Boxes password policy](#tag/storage-boxes/password-policy).
  /// 
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }
}
