//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Api.Models;

/// <summary>
/// UpdateStorageBoxSubaccountRequest (generated from inline request body).
/// Source: PUT /storage_boxes/{id}/subaccounts/{subaccount_id} (requestBody)
/// </summary>
public partial class UpdateStorageBoxSubaccountRequest
{
  /// <summary>
  /// Name of the [Storage Box Subaccount](#tag/storage-box-subaccounts).
  /// 
  /// </summary>
  [MinLength(1)]
  [MaxLength(50)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// A description of [Storage Box Subaccount](#tag/storage-box-subaccounts).
  /// 
  /// </summary>
  [MaxLength(1000)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// 
  /// Note that the set of [Labels](#description/labels) provided in the request will overwrite the
  /// existing one.
  /// 
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }
}
