//
// <auto-generated>
// Hetzner API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/api.spec.json
// API: Hetzner API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Hetzner.Api.Models;

/// <summary>
/// UpdateStorageBoxSnapshotRequest (generated from inline request body).
/// Source: PUT /storage_boxes/{id}/snapshots/{snapshot_id} (requestBody)
/// </summary>
public partial class UpdateStorageBoxSnapshotRequest
{
  /// <summary>
  /// Description of the [Storage Box Snapshot](#tag/storage-box-snapshots).
  /// </summary>
  [MaxLength(1000)]
  [RegularExpression(@"[a-zA-Z0-9-_,:<>+#!\(\)\[\]\{\} ]*")]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// User-defined labels (key/value pairs) for the Resource.
  /// 
  /// Note that the set of [Labels](#description/labels) provided in the request will overwrite the
  /// existing one.
  /// 
  /// For more information, see &quot;[Labels](#description/labels)&quot;.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public Dictionary<string, string?>? Labels { get; set; }
}
