//
// <auto-generated>
// Hetzner Cloud API Client - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/cloud.spec.json
// API: Hetzner Cloud API
// Version: 1.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Hetzner.Cloud;

/// <summary>
/// Request parameters for Get Metrics for a LoadBalancer
/// Operation: GET /load_balancers/{id}/metrics
/// </summary>
public partial class GetLoadBalancerMetricsRequest : BaseRequest
{
  /// <summary>
  /// Type of metrics to get.
  /// </summary>
  [JsonPropertyName("type")]
  public List<string>? Type { get; set; }

  /// <summary>
  /// Start of period to get Metrics for (must be in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
  /// </summary>
  [JsonPropertyName("start")]
  public string? Start { get; set; }

  /// <summary>
  /// End of period to get Metrics for (must be in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
  /// </summary>
  [JsonPropertyName("end")]
  public string? End { get; set; }

  /// <summary>
  /// Resolution of results in seconds.
  /// </summary>
  [JsonPropertyName("step")]
  public string? Step { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Type != null)
      queryParams["type"] = Type;
    if (Start != null)
      queryParams["start"] = Start;
    if (End != null)
      queryParams["end"] = End;
    if (Step != null)
      queryParams["step"] = Step;

    return queryParams.ToQueryString();
  }
}
